name: client
on:
  push:
    branches: ['main']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout/@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: abeesdevjs
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Build and Push Docker
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: abeesdevjs/client
      - name: SSH Remote google cloud and run Docker
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.GOOGLE_CLOUD_HOST}}
          username: ${{secrets.SSH_USER_NAME}}
          script: |
            sudo docker pull abeesdevjs/client:latest 
            sudo docker rm -f $(sudo docker ps -a -q)
            sudo docker run -d -p 3030:3030 abeesdevjs/client
